[package]
name = "mergesort"
version = "0.1.0"
authors = ["jsnar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "*"

[dev-dependencies]
rand = "*"